name: Node Docker Builder
description: Builds node-based Docker images and extracting the version from the Dockerfile and using parent-build logic.

inputs:
  arch:
    description: Architecture to build for (e.g., amd64, arm64)
    required: true
  context:
    description: Context directory for the Docker build
    required: true
  dockerfile:
    description: Path to the Dockerfile relative to the context
    required: true
  tag_prefix:
    description: Prefix for the Docker image tags
    required: true
  version:
    description: Version of the Docker image
    required: true
  push:
    description: Whether to push the image to the registry
    required: false
    default: "false"
  github_token:
    description: GitHub token for authentication with the registry
    required: false
  base_name:
    description: Base name of the node image to extract version from (e.g., "node")
    required: true

outputs:
  tag_prefix:
    description: The prefix used for the Docker image tags
    value: ${{ inputs.tag_prefix }}
  version:
    description: Extracted node version
    value: ${{ steps.extract.outputs.version }}
  ci_build_no:
    description: Build number from parent-build
    value: ${{ steps.call-parent.outputs.ci_build_no }}
  

runs:
  using: "composite"
  steps:
    - name: Extract node version
      id: extract
      shell: bash
      run: |
        version=$(awk -F'-' '{ sub(/^v/, "", $2); print $2 }' "${{ inputs.context }}${{ inputs.dockerfile }}")
        echo "Extracted version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Build using shared logic
      id: call-parent
      uses: rajarshigit2441139/base_action/parent_action@parent_v1.0.2
      with:
        arch: ${{ inputs.arch }}
        context: ${{ inputs.context }}
        dockerfile: ${{ inputs.dockerfile }}
        tag_prefix: ${{ inputs.tag_prefix }}
        version: ${{ steps.extract.outputs.version }}
        push: ${{ inputs.push }}
        github_token: ${{ inputs.github_token }}

